theme: jekyll-theme-minimal
title: Juan Pablo Rodríguez #This is my name
description: This is my description
logo: "/avatar2.jpg?raw=true"
lindekin: "https://www.linkedin.com/in/ingeniero-juan-pablo-rodriguez-pati%C3%B1o/"
