theme: jekyll-theme-minimal
title: Juan Pablo Rodríguez #This is my name
description: This is my description
logo: "/avatar.jpg?raw=true"
  <br><br>
  <a href="https://www.linkedin.com/in/ingeniero-juan-pablo-rodriguez-pati%C3%B1o/">View my Linkedin Profile</a>
